name: example
description: A new Flutter package.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite_entities: 0.0.3
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  source_gen: ^1.2.7
  analyzer: ^5.9.0
  build: ^2.3.1
  flutter_lints: ^2.0.1
  sqflite_entities_generator: 0.0.3

flutter:
  uses-material-design: true